[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools-git-versioning>=2.0,<3",
    "ninja",
    "cmake>=3.15",
]
build-backend = "setuptools.build_meta"

[project]
name = "marinholab-working-needlemanipulation"
description = "Ongoing work on needle manipulation in a collaboration between UTokyo and UoM."
readme = "README.md"
requires-python = ">= 3.10"
license = {text = "MIT"}
authors = [
    {name = "Murilo M. Marinho", email = "murilomarinho@ieee.org"}
]
maintainers = [
    {name = "Murilo M. Marinho", email = "murilomarinho@ieee.org"}
]
dynamic = ["version"]
dependencies = [
    "dqrobotics>=23.4.0a49",
    "quadprog",
    "termcolor",
    "pyyaml",
]

[project.scripts]
needlemanipulation_example = "marinholab.working.needlemanipulation.example:main"
needlemanipulation_example_load_from_file = "marinholab.working.needlemanipulation.example_load_from_file:main"
needlemanipulation_example_create_needle_controller = "marinholab.working.needlemanipulation.example_create_needle_controller:main"

[tool.setuptools.packages.find]
include = ["marinholab*"]

[tool.setuptools.package-data]
"marinholab.working.needlemanipulation" = ["*.yaml", "py.typed", "*.pyi"]

# https://pypi.org/project/setuptools-git-versioning/
[tool.setuptools-git-versioning]
enabled = true
dev_template = "{tag}.{ccount}"
dirty_template = "{tag}.{ccount}"

[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.10"
include = ["marinholab"]
exclude = [
    "**/example*.py",
]
venvPath = "."
venv = ""