"""
Type stubs for the third-party `dqrobotics` package.

`dqrobotics` is a compiled (pybind11) library that ships **no** `py.typed`
marker and no `.pyi` stubs, so every name it exposes is opaque (`Unknown`)
to type checkers and star imports from it fail `reportUndefinedVariable`.

This stub declares the closed set of symbols that
`marinholab.working.needlemanipulation` actually imports, so that the rest of
the codebase can be fully annotated and checked by pyright without globally
weakening the checks. It is placed under `stubs/dqrobotics/` and picked up
via pyright's `stubPath` (see `pyproject.toml`).

If `dqrobotics` ever ships real type information, delete this directory and
drop the `stubPath` setting.
"""

from __future__ import annotations

from typing import Any, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

__all__ = [
    "DQ",
    "k_",
    "i_",
    "j_",
    "E_",
    "conj",
    "dot",
    "cross",
    "Ad",
    "Adsharp",
    "vec4",
    "vec6",
    "vec8",
    "vec3",
    "haminus4",
    "hamiplus4",
    "haminus8",
    "hamiplus8",
    "C4",
    "C8",
    "is_unit",
    "translation",
    "rotation",
    "vec",
]


class DQ:
    """A dual quaternion (8 real components: 4 quaternion + 4 dual part).

    The raw 8-component representation is exposed via :attr:`q`. All the
    arithmetic helpers used by the package (``conj``, ``dot``, ``Ad``, ...)
    operate on this type.
    """

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, q: DQ) -> None: ...
    @overload
    def __init__(self, other: "ndarray[Any, Any]") -> None: ...
    @overload
    def __init__(
        self,
        q0: float,
        q1: float,
        q2: float,
        q3: float,
        e0: float,
        e1: float,
        e2: float,
        e3: float,
    ) -> None: ...

    q: NDArray[np.float64]

    def normalize(self) -> "DQ": ...
    def conj(self) -> "DQ": ...
    def inv(self) -> "DQ": ...
    def norm(self) -> float: ...
    def to_string(self) -> str: ...

    # Component accessors.
    def Q4(self) -> NDArray[np.float64]: ...
    def Q8(self) -> NDArray[np.float64]: ...
    def vec4(self) -> NDArray[np.float64]: ...
    def vec8(self) -> NDArray[np.float64]: ...
    def vec3(self) -> NDArray[np.float64]: ...
    def vec6(self) -> NDArray[np.float64]: ...

    def translation(self) -> "DQ": ...
    def rotation(self) -> "DQ": ...
    def rotation_angle(self) -> float: ...
    def rotation_axis(self) -> "DQ": ...

    def Ad(self, primitive: "DQ") -> "DQ": ...
    def Adsharp(self, primitive: "DQ") -> "DQ": ...

    def generalized_jacobian(self, q: NDArray[np.float64]) -> NDArray[np.float64]: ...

    def exp(self) -> "DQ": ...
    def log(self) -> "DQ": ...
    def pow(self, exponent: "DQ") -> "DQ": ...

    # Operators. ``DQ`` participates in arithmetic with other ``DQ`` values and
    # with real scalars; the reverse operators cover the ``scalar op DQ`` form
    # (e.g. ``1 + 0 * E_``). Operands are typed ``object`` because the exact
    # scalar/duaternion mix the C++ core accepts is not part of its public API.
    def __mul__(self, other: object) -> "DQ": ...
    def __rmul__(self, other: object) -> "DQ": ...
    def __add__(self, other: object) -> "DQ": ...
    def __radd__(self, other: object) -> "DQ": ...
    def __sub__(self, other: object) -> "DQ": ...
    def __rsub__(self, other: object) -> "DQ": ...
    def __neg__(self) -> "DQ": ...

    @overload
    def __eq__(self, other: "DQ") -> bool: ...
    @overload
    def __eq__(self, other: object) -> bool: ...

    def __repr__(self) -> str: ...


# Dual-quaternion unit basis and the dual part of a quaternion.
i_: DQ
j_: DQ
k_: DQ
E_: DQ

# Convenience functions that mirror the ``DQ`` methods.
def conj(q: DQ) -> DQ: ...
def dot(a: DQ, b: DQ) -> DQ: ...
def cross(a: DQ, b: DQ) -> DQ: ...
def Ad(q: DQ, p: DQ) -> DQ: ...
def Adsharp(q: DQ, p: DQ) -> DQ: ...


def vec4(q: DQ) -> NDArray[np.float64]: ...
def vec6(q: DQ) -> NDArray[np.float64]: ...
def vec8(q: DQ) -> NDArray[np.float64]: ...
def vec3(q: DQ) -> NDArray[np.float64]: ...


# The (matrix) half of a dual quaternion: the 4x4 and 8x8 rotation matrices
# built from the pure / full dual quaternion.
def haminus4(q: DQ) -> NDArray[np.float64]: ...
def hamiplus4(q: DQ) -> NDArray[np.float64]: ...
def haminus8(q: DQ) -> NDArray[np.float64]: ...
def hamiplus8(q: DQ) -> NDArray[np.float64]: ...


# The 4x4 and 8x8 constant coupling matrices of the dual-quaternion
# representation.
def C4() -> NDArray[np.float64]: ...
def C8() -> NDArray[np.float64]: ...


def is_unit(q: DQ) -> bool: ...
def translation(q: DQ) -> DQ: ...
def rotation(q: DQ) -> DQ: ...
def vec(q: DQ) -> NDArray[np.float64]: ...
